const dataBaseProdutos = [
    {
      id: 1,
      nameItem: "Darth Maul",
      img: "./img/Darth Maul.png",
      price: 199.50.toFixed(2),
      category:"STW",
      description:"Sith Darth Maul",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 2,
      nameItem: "Aldebaran",
      img: "./img/Aldebaran.png",
      price: 90.00.toFixed(2),
      category:"CDZ",
      description:"Aldebaran de Touro",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 3,
      nameItem: "Darth Vader",
      img: "./img/Vader.png",
      price: 199.99.toFixed(2),
      category:"STW",
      description:"Sith Darth Vader",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 4,
      nameItem: "Kamus",
      img: "./img/Kamus.png",
      price: 121.00.toFixed(2),
      category:"CDZ",
      description:"Kamus de Aquário",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 5,
      nameItem: "Leia Skywalker",
      img: "./img/Leia Organa.png",
      price: 149.90.toFixed(2),
      category:"STW",
      description:"General Leia Organa",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 6,
      nameItem: "Milo",
      img: "./img/Milo.png",
      price: 85.49.toFixed(2),
      category:"CDZ",
      description:"Milo de Escorpião",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 7,
      nameItem: "Storm Trooper",
      img: "./img/Trooper.png",
      price: 29.99.toFixed(2),
      category:"STW",
      description:"Soldado Imperial",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 8,
      nameItem: "Mu",
      img: "./img/Mu.png",
      price: 123.45.toFixed(2),
      category:"CDZ",
      description:"Mu de Áries",
      addCart: "Adicionar ao carrinho",
    },
    {
      id: 9,
      nameItem: "Obi Wan Kenobi",
      img: "./img/Obi Wan.png",
      price: 567.89.toFixed(2),
      category:"STW",
      description:"Cavalier da Ordem Jedy",
      addCart: "Adicionar ao carrinho",
  },
  {
    id: 10,
    nameItem: "Aiolos",
    img: "./img/Sagitario.png",
    price: 599.09.toFixed(2),
    category:"CDZ",
    description:"Aiolos de Sagitário",
    addCart: "Adicionar ao carrinho",
  }
];
export default dataBaseProdutos;
